[package]
name = "bs_agg_ots"
version = "0.1.0"
authors = ["Sam Kim <skim13@cs.stanford.edu>"]
edition = "2018"

[dependencies]
curve25519-dalek = "2"
rand_core = "0.5"
sha2 = "0.8"
error-chain = "0.12.0"
rand = "0.4"
time = "0.1.40"
